[package]
name = "data_collection"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
reqwest = "0.12.9"
select = "0.6.0"
serde = "1.0.215"
serde_json = "1.0.132"
surrealdb = "2.0.4"
tokio = "1.41.1"
